version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 200000000ununa
- name: bob
  coins:
  - 100000000ununa
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000ununa
validators:
- name: alice
  bonded: 100000000ununa
